eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/
  instance:
    instance-id: ${spring.application.name}-${random.int}
    hostname: localhost
